(*
 * qVi Language Grammar
 * *)

(*
 * Lexical Grammar
 * --------------------------------------------------------------------------
 *)

Letter          = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
                | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" |"Z"
                | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" |"m"
                | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" .

Digit           = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" .
HexDigit        = Digit | "a" | "b" | "c" | "d" | "e" | "f" | "A" | "B" | "C" | "D" | "E" | "F" .
BinaryDigit     = "0" | "1" .

Identifier      = ( Letter | "_" ) { Letter | Digit | "_" } .
QualifiedName   = Identifier { "::" Identifier } .
FileName        = ( Letter | Digit | "_" | "." | "/" | "-" ) { Letter | Digit | "_" | "." | "/" | "-" } .

IntegerLiteral  = ( "0x" HexDigit { HexDigit | "_" } )
                | ( "0b" BinaryDigit { BinaryDigit | "_" } )
                | ( Digit { Digit | "_" } ) .

FloatLiteral    = Digit { Digit | "_" } "." Digit { Digit | "_" } [ ( "f" | "F" ) ]
                | Digit { Digit | "_" } ( "f" | "F" ) .

Number          = FloatLiteral | IntegerLiteral .
StringLiteral   = '"' { StringCharacter } '"' [ "b" ] .
CharLiteral     = "'" { CharCharacter } "'" .

LineComment     = "//" { LineCommentCharacter } NewLine .
NestedComment   = "/{" { NestedComment | NestedCommentCharacter } "/}" .


(*
 * Top-Level Declarations
 * --------------------------------------------------------------------------
 *)

SourceFile          = { TopLevelItem } .

TopLevelItem        = Directive
                    | Declaration
                    | Statement
                    | ";" .

Directive           = "#test" | "#[" Identifier "]" .

Declaration         = QualifiedName ":" [ LanguageTag ] Definition ";".

Definition          = VariableDefinition
                    | FunctionDefinition
                    | TypeDefinition
                    | EnumDefinition
                    | Block .


VariableDeclaration = QualifiedName ":" VariableDefinition .
VariableDefinition  = DataType [ "=" Expression ]

TypeDefinition      = ( "struct" | "union" ) "{" { FieldDeclaration } "}" .
FieldDeclaration    = Identifier ":" DataType [ "=" Expression ] ";" .

FunctionDefinition  = "(" [ ParameterList ] ")" [ "using" Identifier ] [ "->" DataType ] Block .
ParameterList     = [ VariableDeclaration { "," VariableDeclaration } ] .


(*
 * Types
 * --------------------------------------------------------------------------
 *)

IntType         = "i8" | "i16" | "i32" | "i64"
                | "u8" | "u16" | "u32" | "u64" .

FloatType       = "f32" | "f64" .
BaseType        = IntType | FloatType | "bool" | "void" .

Qualifier       = "const" | "embed" | "fluid" | "alloc" .

DataType        = [ Qualifier ] ( TypeConstructor ) { TypeDecorator } .

TypeConstructor = BaseType
                | QualifiedName
                | StructType
                | EnumType
                | FunctionType .

StructType      = ( "struct" | "union" ) "{" { Binding ";" } "}" .

EnumType        = "enum" [ ":" IntType ] "{" [ EnumMember { "," EnumMember } [ "," ] ] "}" .
EnumMember      = Identifier [ "=" Expression ] .

TypeDecorator   = "^"                                (* Pointer *)
                | "[" [ Expression | Qualifier ] "]" (* Array or Slice *) .

FunctionType    = "(" [ DataType { "," DataType } ] ")" "->" DataType .


(*
 * Statements
 * --------------------------------------------------------------------------
 *)

Statement       = Block
                | IfStatement
                | LoopStatement
                | CaseStatement
                | ReturnStatement
                | FlowControlStatement
                | ImportStatement
                | PrintStatement
                | ExpressionStatement .

Block           = "{" { TopLevelItem } "}"
                | ":" Statement .

IfStatement     = "if" Expression Block { "else" "if" Expression Block } [ "else" Block ] .

LoopStatement   = "loop" Iterable [ "as" [ "&" ] Identifier ] [ "at" [ "&" ] Identifier [ ":" DataType ] ] Block .

CaseStatement   = "case" Expression "{" { CaseClause } "}" .
CaseClause      = ( "when" Expression | "else" ) Block .

ReturnStatement = "return" [ Expression { "," Expression } ] ";" .
FlowControlStatement = ( "break" | "continue" ) [ Identifier ] ";" .

ImportStatement = "import" [ LanguageTag ] FileName "as" Identifier [ ":" Definition | ";" ] .
PrintStatement  = StringLiteral [ Expression ] { "," Expression } ";" .
ExpressionStatement = Expression [ "=" Expression ] ";" .


(*
 * MATLAB-style Ranges
 * --------------------------------------------------------------------------
 *)

Range           = [ Expression ] ":" [ Expression ] [ ":" [ Expression ] ]
                | ":" .

Iterable        = Range | Expression .


(*
 * Expressions
 * --------------------------------------------------------------------------
 *)

Expression      = LogicalOr .

LogicalOr       = LogicalAnd   { "||" LogicalAnd } .
LogicalAnd      = BitOr        { "&&" BitOr } .
BitOr           = BitXor       { "|" BitXor } .
BitXor          = BitAnd       { "^" BitAnd } .
BitAnd          = Equality     { "&" Equality } .
Equality        = Relational   { ( "==" | "!=" ) Relational } .
Relational      = Shift        { ( "<" | "<=" | ">" | ">=" ) Shift } .
Shift           = Additive     { ( "<<" | ">>" ) Additive } .
Additive        = Multiplicative { ( "+" | "-" ) Multiplicative } .
Multiplicative  = CastExpr     { ( "*" | "/" | "%" ) CastExpr } .
CastExpr        = Unary        { ( "->" | "=>" ) DataType } .

Unary           = ( "+" | "-" | "&" | "^" | "!" | "~" | "++" | "--" ) Unary
                | Postfix .

Postfix         = Primary { Selector | SliceOrIndex | FunctionCall } .

Selector        = "." Identifier .
SliceOrIndex    = "[" SliceElement { "," SliceElement } "]" .  (* Multi-dimensional slicing *)
SliceElement    = Range | Expression .

FunctionCall    = "(" [ Expression { "," Expression } ] ")" .

Primary         = QualifiedName
                | Number
                | StringLiteral
                | CharLiteral
                | "true" | "false" | "null"
                | "(" Expression ")"
                | ArrayLiteral
                | StructLiteral .

ArrayLiteral    = "[" [ Expression { "," Expression } [ "," ] ] "]" .
StructLiteral   = "{" [ FieldInit { "," FieldInit } [ "," ] ] "}" .
FieldInit       = [ Identifier "=" ] Expression .

LanguageTag     = "[" Identifier "]" .
