id = "qVi-lang"
name = "qVi Language Support"
version = "0.0.2"
schema_version = 1
description = "Language support and LSP integration for qVi."

[language_servers.qVi-lsp]
name = "qVi-lang LSP"
languages = ["qVi-lang"]
