id = "qVi-lang"
name = "qVi Language Support"
version = "0.0.2"
schema_version = 1
description = "Language support and LSP integration for qVi."

[language_servers.qvi-lsp]
name = "qVi LSP"
languages = ["qVi"]
